services:
  adobe-hdfs:
    image: mongo:latest
    container_name: ADOBE
    restart: always
    ports:
      - "27018:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=adobe_admin
      - MONGO_INITDB_ROOT_PASSWORD=adobe_hdfs_pass
    volumes:
      - hdfs_data:/data/db
      - ./hdfs_config:/etc/mongod
    command: mongod --config /etc/mongod/hdfs.conf

volumes:
  hdfs_data:
